apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-api-deployment
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-api-pod
  template:
    metadata:
      labels:
        app: gateway-api-pod
    spec:
      containers:
      - name: gateway-api
        image: searchengine/gateway.webapi
        imagePullPolicy: Never
        ports:
        - containerPort: 8080       
---
apiVersion: v1
kind: Service
metadata:
  namespace: services
  name: gateway-api-service
spec:
  selector:
    app: gateway-api-pod
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30000
