apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagedownloader-worker-deployment
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pagedownloader-worker-pod
  template:
    metadata:
      labels:
        app: pagedownloader-worker-pod
    spec:
      containers:
      - name: pagedownloader-worker
        image: searchengine/pagedownloader.worker
        imagePullPolicy: Never
