apiVersion: apps/v1
kind: Deployment
metadata:
  name: tagextractor-worker-deployment
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tagextractor-worker-pod
  template:
    metadata:
      labels:
        app: tagextractor-worker-pod
    spec:
      containers:
      - name: tagextractor-worker
        image: searchengine/tagextractor.worker
        imagePullPolicy: Never
