apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlextractor-worker-deployment
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: urlextractor-worker-pod
  template:
    metadata:
      labels:
        app: urlextractor-worker-pod
    spec:
      containers:
      - name: urlextractor-worker
        image: searchengine/urlextractor.worker
        imagePullPolicy: Never
