apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlregister-api-deployment
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: urlregister-api-pod
  template:
    metadata:
      labels:
        app: urlregister-api-pod
    spec:
      containers:
      - name: urlregister-api
        image: searchengine/urlregister.webapi
        imagePullPolicy: Never
        ports:
        - containerPort: 8080       
---
apiVersion: v1
kind: Service
metadata:
  namespace: services
  name: urlregister-api-service
spec:
  type: LoadBalancer
  selector:
    app: urlregister-api-pod
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http

