apiVersion: v1
kind: Secret
metadata:
  name: urlextractor-database-secret
  namespace: databases
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: UGFzc3dvcmQxMjMu
  database: VXJsRXh0cmFjdG9y
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlextractor-database
  namespace: databases
  labels:
    app: urlextractor-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: urlextractor-database
  template:
    metadata:
      labels:
        app: urlextractor-database
    spec:
      containers:
      - name: urlextractor-database
        image: searchengine/urlextractor.database
        imagePullPolicy: Never
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: urlextractor-database-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: urlextractor-database-secret
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: urlextractor-database-secret
              key: database
---
apiVersion: v1
kind: Service
metadata:
  name: urlextractor-database-service
  namespace: databases
spec:
  selector:
    app: urlextractor-database
  type: NodePort
  ports:
    - port: 5432
