apiVersion: v1
kind: Secret
metadata:
  name: urlregister-database-secret
  namespace: databases
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: UGFzc3dvcmQxMjMu
  database: VXJsUmVnaXN0ZXI=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlregister-database-deployment
  namespace: databases
spec:
  replicas: 1
  selector:
    matchLabels:
      app: urlregister-database-pod
  template:
    metadata:
      labels:
        app: urlregister-database-pod
    spec:
      containers:
      - name: urlregister-database
        image: postgres:16.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: urlregister-database-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: urlregister-database-secret
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: urlregister-database-secret
              key: database
---
apiVersion: v1
kind: Service
metadata:
  name: urlregister-database-service
  namespace: databases
spec:
  selector:
    app: urlregister-database-pod
  type: NodePort
  ports:
    - port: 5432
